### ISSUE TITLE
Strange Bug

### ISSUE THREAD

**Issue by Tab1138** [pupnewfster/GGSkyblock#19] opened 2019-02-03 19:15 UTC
I was leveling up magic at 27 all my stats went back to 1 in all skills. I kept on clicking and it would not go up. Then out of no where all my stats returned I went to move then the whole game crashed. I got both crash reports here. Also when you hold a stack of clay buckets when it is raining it creates a dupe bug where all your clay buckets are full and still in a stack with extra full buckets in your inventory. Here is the first report. 
-----------------------------------
https://pastebin.com/DHfSq5WM

**-----------------------Here is the second when the game crashed----------------------**

https://pastebin.com/KXN310w6

I hope this helps I am enjoying the pack so far .

**Comment by pupnewfster** [comment] 2019-02-03 19:59
I will look into it. (I edited your issue to put the crash reports into pastebin to make them easier to read.)

I reported the clay bucket bug to the mod https://github.com/MJRLegends/CollectingRain/issues/4

And as for the crash it seems to be some issue in either CompatSkills or Reskillable, so I will try to find and fix it given I am one of the devs for both of those. Though given where the error is pointing to I am not sure exactly what is wrong. Does it crash again if you reopen up mc? Given I am not quite sure how to reproduce the crash and think it may partially be a fluke.

Was the crash on a server? Given my only idea is that maybe the networking didn't line up quite right for some reason and tried to run code after the client left/crashed.

**Comment by pupnewfster** [comment] 2019-02-03 20:09
Actually I think the second crash is due to an invalid state caused by the first crash, which VanillaFix probably kept from closing the game. And it was trying to continue with data that was no longer valid.

**Comment by Tab1138** [comment] 2019-02-04 01:34
I have been playing for hours since then and haven't had it happen again.
So I guess it was a fluke like you said. It was on a single player world.
It was just a strange bug right when I tried to level magic past level 27.
This mod pack is really fun I am really enjoying it.

**Comment by pupnewfster** [comment] 2019-02-06 23:42
Next version lets the buckets stack again, and has an updated version of reskillable that should clean some stuff up (granted I am still not exactly sure as to why the crash happened so hopefully it was just some fluke chance).

**Closed by pupnewfster** 2019-02-06 23:42 UTC
